complete -c pkg -n '__fish_use_subcommand' -f -a "--check-mirror" -d "Force a re-check of availability of mirrors"
complete -c pkg -n '__fish_use_subcommand' -f -a "autoclean" -d "Remove outdated packages from the cache"
complete -c pkg -n '__fish_use_subcommand' -f -a "clean" -d "Remove all packages from the cache"
complete -c pkg -n '__fish_use_subcommand' -f -a "files" -d "Show all files installed by packages"
complete -c pkg -n '__fish_use_subcommand' -f -a "install" -d "Install specified packages"
complete -c pkg -n '__fish_use_subcommand' -f -a "list-all" -d "List all packages available in repositories"
complete -c pkg -n '__fish_use_subcommand' -f -a "list-installed" -d "List installed packages"
complete -c pkg -n '__fish_use_subcommand' -f -a "reinstall" -d "Reinstall specified packages"
complete -c pkg -n '__fish_use_subcommand' -f -a "search" -d "Search packages by query"
complete -c pkg -n '__fish_use_subcommand' -f -a "show" -d "Show metadata for specified packages"
complete -c pkg -n '__fish_use_subcommand' -f -a "uninstall" -d "Uninstall specified packages"
complete -c pkg -n '__fish_use_subcommand' -f -a "upgrade" -d "Upgrade all installed packages"
complete -c pkg -n '__fish_use_subcommand' -f -a "update" -d "Update package manager databases"
